import type { Metadata } from "next";
import "./globals.css";
import { Oxanium, Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Presentation Devstage",
  description: "Generated by create next app",
};

const oxanium = Oxanium({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-oxanium",
});
const montserrat = Montserrat({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="bg-black">{children}</body>
    </html>
  );
}
